FROM node:14-alpine as bld
ENV PATH /app/node_modules/.bin:$PATH
WORKDIR /app
COPY package*.json /app
RUN npm install

FROM node:14-alpine as tst
ENV CI=true
WORKDIR /app
RUN pwd
COPY --from=bld /app/node_modules /app/node_modules
COPY . .
RUN npm test || true

FROM node:14-alpine as dlv
ENV CI=true
WORKDIR /app
COPY --from=bld /app/node_modules /app/node_modules
COPY . .
CMD [ "npm", "start" ]
